[[section-introduction-and-goals]]
== Introduction and Goals

[role="arc42help"]
****
Relevant requirements and the driving forces we must consider. These include

* underlying business goals, essential features and functional requirements for the system
* quality goals for the architecture
* relevant stakeholders and their expectations

****

=== Requirements Overview

[role="arc42help"]
****
.Contents
Monopolizing transaction flow for arbitrage batching with miner support.

.Motivation
From the point of view of the end users a system is created or modified to
improve support of a business activity and/or improve the quality. YCabal's key result
will be the enabling of gas-free transactons while also reducing arbitrage externalities. 

How to decompose an application into microservices - as described below the application consists of several services. For example, bank accounts are managed by one service, money transfers by another service.

 Using an event-driven architecture to achieve data consistency - rather than using traditional distributed transaction to maintain database consistency this application uses an eventually consistent, event-driven approach.

 Using event sourcing to implement the event-driven architecture - the domain logic consists of Domain-Driven Design (DDD) aggregates that using event sourcing.

 How event sourcing enables deployment flexibility - the application can either be deployed as a monolith or as microservices.

 Using Command Query Responsibility Segregation (CQRS) - update requests (HTTP POSTs and PUTs) and view requests (HTTP GETs) are handled by separate services.

> There are two services running - The Product Offering and the Product Offering Service 


.Form
- JSON RPC 2.0 Service Provider 
- Archival / Sync'd Ethereum Nodes
- Websocket Access for end users as well as RPC
- Message Queue management 
- API spec for miners and end users to utilize 


****

=== Quality Goals

[role="arc42help"]
****
.Contents
The top three (max five) quality goals for the architecture whose fulfillment is of highest importance to the major stakeholders. We really mean quality goals for the architecture. Don't confuse them with project goals. They are not necessarily identical.

.Motivation
You should know the quality goals of your most important stakeholders, since they will influence fundamental architectural decisions. Make sure to be very concrete about these qualities, avoid buzzwords.
If you as an architect do not know how the quality of your work will be judged …

.Form
A table with quality goals and concrete scenarios, ordered by priorities
****

=== Stakeholders

[role="arc42help"]
****
.Contents
Explicit overview of stakeholders of the system, i.e. all person, roles or organizations that

* should know the architecture
* have to be convinced of the architecture
* have to work with the architecture or with code
* need the documentation of the architecture for their work
* have to come up with decisions about the system or its development

.Motivation
All parties involved in development of the YCabal or affected by this system.

.Form
Table with role names, person names, and their expectations with respect to the architecture and its documentation. Some Roles are 'undefined' (i.e. Community engagement / liasion )
****

[options="header",cols="1,2,2"]
|===
|Role/Name|Contact|Expectations
| _Front End UI/UX  | _<Contact-1>_ | _SushiSwap_
| _Protocol Engineering _ | _<Contact-2>_ | _SushiSwap_
| _Backend Operations | _x48_ | _Yearn Finance_
| _Community Liasion_ | _<Contact-2>_ | _SushiSwap (undefined)_
| _<Role-2>_ | _<Contact-2>_ | _<Expectation-2>_
|===
