[[section-architecture-constraints]]
== Architecture Constraints


[role="arc42help"]
****
.Contents
Any requirement that constrains software architects in their freedom of design and implementation decisions or decision about the development process.

 Constraints sometimes go beyond individual systems and are valid for whole organizations and companies.

.Motivation
Architects should know exactly where they are free in their design decisions and where they must adhere to constraints.
Constraints must always be dealt with; they may be negotiable, though.

.General Constraints

- Downtime. If for any reason node has to be taken down for maintenance there will
be no node left. There will be downtime when for example there is a need to
upgrade a version of ParityGeth.


- Falling out of sync. Parity is great but not flaweless. It may occasionally fall
out of sync for various reasons. Having multiple nodes allows us to temporarly
re-route traffic from nodes which have fallen behind and query nodes which are
in-sync.

- Distributing load. There is only a certain level of requests/second on json-rpc
that a single Parity node can sustain. Json-rpc interface becomes slow over this
level and Parity node falls out of sync. This is especially important if node(s)
is used from web dapp interface and number, and you can observe daily spikes in
user engagement.

****
