[[section-solution-strategy]]
== Solution Strategy


[role="arc42help"]
****
.Contents
Fundamental decisions and solution strategies, that shape the system's architecture.

* technology decisions
* decisions about the top-level decomposition of the system, e.g. usage of an architectural pattern or design pattern
* decisions on how to achieve key quality goals
* relevant organizational decisions, e.g. selecting a development process or delegating certain tasks to third parties.

.Motivation
These decisions form the cornerstones for your architecture. They are the basis for many other detailed decisions or implementation rules.

.Decisions 

KDB+ for Database Technology
Redis for Network Management
Terraform
Docker for Hypervisor/Container
DynamoDB/PostGres for Service/Logging Persistance

=== RPC Layer 

A list of URL of out Parity node should be kept in DynamoDB. There is also a
special URL called leader that points to Infura/AlchemyAPI

` eth_getBlockNumber` should be run on each of the nodes from the list every 60
seconds. The result is compared with the leader. For the node to be deemed
healthy it has to respond and be no more than 10 blocks behind Infura. The
health status of each node is saved to DynamoDB/PostGres

Change of health status of any node triggers regeneration of proxy config. Proxy
config is simply an nginx .conf file that configures an upstream service which
load-balances load between our nodes.

If none of our nodes is healthy the generated config proxies all requests to [This is Open] as a fallback. 
the config file is uploaded to S3 bucket.

- Uploading config file to S3 bucket triggers update of ECS Service that runs
nginx container with with generated config. Standard GitDevOps

- Monitoring nodes
The upside of using AWS services is that they come with default metrics
out-of-box


.Central Dogma (the 'black box')
> the core guts of the backbone network


Writing atomically to a database and a message broker can add unnecessary code complexity

Message Broker unavailability would force decisions about each microservice's trade-offs between availability and consistency

+ *Solution*
Separate the concern of managing inter-service communication by using an event-driven Message Relay

- RedisGears can be used to easily implement the Transactional Outbox pattern by listening for events within 

Redis databases and relaying event notifications (write-behind pattern) to a Message Broker for downstream inter-service communication
Redis-based microservices would avoid code complexity, concerns with Message Broker unavailability, and performance overhead

.Observability
**Challenge**
Observability, tracing, and auditing of Choreography-based Sagas is difficult across a decoupled chain of microservices

Solution

- Event Sourcing implies recording every microservice's state change as an immutable event; acting as a source of truth
- It is composed of a Message Broker and Event Store

- Based on the or dered sequence of events persisted in the event store, a microservice can replay/rebuild its system state by reprocessing recorded events at any time

- Redis Streams is an immutable in-memory append-only log data structure perfectly suited and used as an Event Store
- Visualizing a stream of events can provide real-time observability of the system's state and instant recovery/replay

.Questions

Load Balancer - HAProxy or alt?s

System Recovery 

Incident Resposne Planning 

Legal Questionsz - minimal

****
